#!/usr/bin/env bash
set -euo pipefail

# Source cache fetcher for weblog research notes.
# Each entry: slug|url|description
sources=(
    "01-endor-labs-bitwarden-cli|https://www.endorlabs.com/learn/shai-hulud-the-third-coming----inside-the-bitwarden-cli-2026-4-0-supply-chain-attack|Endor Labs — bw1.js reverse engineering"
    "02-bleepingcomputer-bw-cli|https://www.bleepingcomputer.com/news/security/bitwarden-cli-npm-package-compromised-to-steal-developer-credentials/|BleepingComputer — incident overview"
    "03-thehackernews-bw-cli|https://thehackernews.com/2026/04/bitwarden-cli-compromised-in-ongoing.html|The Hacker News — campaign context"
    "04-aikido-shai-hulud|https://www.aikido.dev/blog/shai-hulud-npm-bitwarden-cli-compromise|Aikido — worm propagation analysis"
    "05-cybernews-bw-cli|https://cybernews.com/security/bitwarden-cli-npm-package-compromised-with-malware/|Cybernews — affected developer count"
    "06-securityboulevard-butlerian|https://securityboulevard.com/2026/04/the-butlerian-jihad-compromised-bitwarden-cli-deploys-npm-worm-poisons-ai-assistants-and-dumps-github-secrets/|Security Boulevard — Butlerian Jihad analysis"
    "07-bitwarden-statement|https://community.bitwarden.com/t/bitwarden-statement-on-checkmarx-supply-chain-incident/96127|Bitwarden official statement"
    "08-bitwarden-passkey-infostealer|https://community.bitwarden.com/t/safety-of-passkeys-stored-in-bitwarden-if-there-is-a-password-stealing-info-stealer-breach/96181|Bitwarden community — passkey vs. infostealer risk"
    "09-bitwarden-cli-help|https://bitwarden.com/help/cli/|Bitwarden Help — CLI session-key model (BW_SESSION)"
    "10-aegis-readme|https://github.com/beemdevelopment/Aegis|Aegis project README"
    "11-aegis-faq|https://raw.githubusercontent.com/beemdevelopment/Aegis/master/FAQ.md|Aegis FAQ on backups"
    "12-aegis-cloud-sync-issue|https://github.com/beemdevelopment/Aegis/issues/258|Aegis cloud-sync issue thread"
)

ua="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
out_dir="research/passkeys-are-not-enough"
force=0
list_only=0

usage() {
    cat <<EOF
Usage: $0 [--force] [--list] [--dir PATH]

  --force       re-fetch sources even if cached files already exist
  --list        print the source list and exit (no network calls)
  --dir PATH    override the output directory (default: $out_dir)
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --force) force=1; shift ;;
        --list) list_only=1; shift ;;
        --dir) out_dir=$2; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "unknown arg: $1" >&2; usage >&2; exit 2 ;;
    esac
done

if [[ $list_only -eq 1 ]]; then
    for entry in "${sources[@]}"; do
        IFS='|' read -r slug url desc <<<"$entry"
        printf '%-36s  %s\n  %s\n\n' "$slug" "$desc" "$url"
    done
    exit 0
fi

command -v curl >/dev/null || { echo "fatal: curl is required" >&2; exit 1; }
have_pandoc=1
if ! command -v docker >/dev/null; then
    have_pandoc=0
    echo "warn: docker not found — raw HTML will be saved but no .md extraction" >&2
fi
pandoc_image="pandoc/core:latest"

mkdir -p "$out_dir"

failures=0
for entry in "${sources[@]}"; do
    IFS='|' read -r slug url desc <<<"$entry"
    html_path="$out_dir/$slug.html"
    md_path="$out_dir/$slug.md"

    if [[ -s "$html_path" && $force -eq 0 ]]; then
        printf '[skip] %s\n' "$slug" >&2
        continue
    fi

    if curl -fsSL --retry 3 --retry-delay 2 -A "$ua" -o "$html_path.tmp" "$url"; then
        mv "$html_path.tmp" "$html_path"
        bytes=$(wc -c <"$html_path" | tr -d ' ')
        printf '[ok]   %s  (%s bytes)\n' "$slug" "$bytes" >&2
        if [[ $have_pandoc -eq 1 ]]; then
            docker run --rm \
                --user "$(id -u):$(id -g)" \
                -v "$PWD/$out_dir:/data" \
                "$pandoc_image" \
                -f html -t gfm -o "/data/$slug.md" "/data/$slug.html" 2>/dev/null || \
                printf '[warn] pandoc failed for %s\n' "$slug" >&2
        fi
    else
        rm -f "$html_path.tmp"
        printf '[fail] %s  %s\n' "$slug" "$url" >&2
        failures=$((failures + 1))
    fi
done

# Regenerate INDEX.md from the source list.
index_path="$out_dir/INDEX.md"
{
    printf '# Source cache — passkeys-are-not-enough\n\n'
    printf 'Generated by `fetch-sources.sh` on %s.\n\n' "$(date -u +'%Y-%m-%d %H:%M UTC')"
    printf '| # | Source | URL | HTML | MD |\n'
    printf '|---|--------|-----|------|----|\n'
    for entry in "${sources[@]}"; do
        IFS='|' read -r slug url desc <<<"$entry"
        num=${slug%%-*}
        html_link="[html](./$slug.html)"
        md_link="—"
        [[ -s "$out_dir/$slug.md" ]] && md_link="[md](./$slug.md)"
        printf '| %s | %s | <%s> | %s | %s |\n' "$num" "$desc" "$url" "$html_link" "$md_link"
    done
} >"$index_path"
printf '[ok]   INDEX.md regenerated\n' >&2

if [[ $failures -gt 0 ]]; then
    printf 'done with %d failure(s)\n' "$failures" >&2
    exit 1
fi
printf 'done\n' >&2
