on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  weblog_import:
    runs-on: ubuntu-latest
    name: weblog.lol
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
            # - id: weblog_import
            #   uses: neatnik/weblog.lol@v1
      - run: php -f weblog-import.php $ADDRESS $WEBLOG_API_KEY
        shell: bash
        env:
          ADDRESS: xd1
          WEBLOG_API_KEY: ${{ secrets.WEBLOG_API_KEY }}
